version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=dbSintec
      - POSTGRES_USER=charli
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql
    